const btspublicConfig={
  content:[
    {
      title:"airPollutant",
      subtitle:"",
      // checkbox:"radio",//单选框
      checkbox:"checkbox",//复选框
      content:[
        {
          title:"医疗",
          subtitle:"",
          key:"WPTSpecial.UpdatePOICategory",
          value:0,
        },
        {
          title:"幼儿园",
          subtitle:"",
          key:"WPTSpecial.UpdatePOICategory",
          value:1,
        },
        {
          title:"公园",
          subtitle:"",
          key:"WPTSpecial.UpdatePOICategory",
          value:2,
        },
        {
          title:"ATM",
          subtitle:"",
          key:"WPTSpecial.UpdatePOICategory",
          value:3,
        },
        {
          title:"餐厅",
          subtitle:"",
          key:"WPTSpecial.UpdatePOICategory",
          value:4,
        },
        {
          title:"购物",
          subtitle:"",
          key:"WPTSpecial.UpdatePOICategory",
          value:5,
        },
        {
          title:"生活服务",
          subtitle:"",
          key:"WPTSpecial.UpdatePOICategory",
          value:6,
        },
        {
          title:"休闲娱乐",
          subtitle:"",
          key:"WPTSpecial.UpdatePOICategory",
          value:7,
        },
      ]
    },
    {
      title:"chartControl",
      subtitle:"",
      content:[
        {
          title:"扩展",
          subtitle:"",
          key:"",
          value:"",
          select:false,
        },
        {
          title:"全部隐藏",
          subtitle:"",
          key:"WPTPopulation.ShowDistrubutionChart",
          value:true,
        },
      ]
    },
    ,
    {
      title:"mapbox",
      subtitle:"",
      content:[
        {
          title:"公共服务信息点",
          subtitle:"",
          key:"WPTEnvi.ShowEnviAdditionChart",
          value:true,
          select:false,
        },
      ]
    },
  ]
  }
  export default btspublicConfig;
